services:
  realtime-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  vue-app:
    build: ./frontend
    ports:
      - "5173:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
